# Generated by Django 2.1.2 on 2018-10-23 11:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('creator', 'name')},
        ),
    ]
