# Generated by Django 2.2b1 on 2019-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_lists', '0004_list_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='follows',
            field=models.ManyToManyField(db_index=True, related_name='lists', to='openbook_follows.Follow'),
        ),
    ]
