# Generated by Django 2.2b1 on 2019-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_lists', '0005_auto_20190331_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='follows',
            field=models.ManyToManyField(related_name='lists', to='openbook_follows.Follow'),
        ),
    ]
