# Generated by Django 2.1.5 on 2019-02-03 15:59

from django.db import migrations, models
import openbook_communities.validators


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='users',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[openbook_communities.validators.community_name_characters_validator], verbose_name='name'),
        ),
    ]
