# Generated by Django 2.1.5 on 2019-02-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0002_auto_20190203_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityModeratorUserActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('action_type', models.CharField(choices=[('B', 'Ban'), ('U', 'Unban')], editable=False, max_length=2)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators_user_actions_logs', to='openbook_communities.Community')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='communityinvite',
            unique_together={('invited_user', 'community', 'creator')},
        ),
    ]
