# Generated by Django 2.1.5 on 2019-02-07 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0005_auto_20190205_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='starrers',
            field=models.ManyToManyField(related_name='favorite_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
