# Generated by Django 2.1.5 on 2019-02-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0006_community_starrers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='circle',
        ),
    ]
