# Generated by Django 2.1.5 on 2019-02-08 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0007_remove_community_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='joined_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
