# Generated by Django 2.1.5 on 2019-02-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0008_auto_20190208_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='members_can_invite_members',
            field=models.BooleanField(default=True, verbose_name='members can invite members'),
        ),
    ]
