# Generated by Django 2.1.5 on 2019-02-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0009_community_members_can_invite_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members_can_invite_members',
        ),
        migrations.AddField(
            model_name='community',
            name='invites_enabled',
            field=models.BooleanField(default=True, verbose_name='invites enabled'),
        ),
    ]
