# Generated by Django 2.1.5 on 2019-02-11 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0010_auto_20190209_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('action_type', models.CharField(choices=[('B', 'Ban'), ('U', 'Unban'), ('AM', 'Add Moderator'), ('RM', 'Remove Moderator'), ('AA', 'Add Administrator'), ('RA', 'Remove Administrator')], editable=False, max_length=5)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='openbook_communities.Community')),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='communityadministratoruseractionlog',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='communityadministratoruseractionlog',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityadministratoruseractionlog',
            name='target_user',
        ),
        migrations.RemoveField(
            model_name='communitymoderatoruseractionlog',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitymoderatoruseractionlog',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='communitymoderatoruseractionlog',
            name='target_user',
        ),
        migrations.DeleteModel(
            name='CommunityAdministratorUserActionLog',
        ),
        migrations.DeleteModel(
            name='CommunityModeratorUserActionLog',
        ),
    ]
