# Generated by Django 2.1.5 on 2019-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0011_auto_20190211_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitylog',
            name='action_type',
            field=models.CharField(choices=[('B', 'Ban'), ('U', 'Unban'), ('AM', 'Add Moderator'), ('RM', 'Remove Moderator'), ('AA', 'Add Administrator'), ('RA', 'Remove Administrator'), ('RP', 'Remove Post'), ('RPC', 'Remove Post Comment')], editable=False, max_length=5),
        ),
    ]
