# Generated by Django 2.1.5 on 2019-02-18 10:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0012_auto_20190214_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='community',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='', verbose_name='cover'),
        ),
    ]
