# Generated by Django 2.1.5 on 2019-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0012_auto_20190212_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.CharField(max_length=1500, null=True, verbose_name='rules'),
        ),
    ]
