# Generated by Django 2.1.5 on 2019-02-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0013_auto_20190218_1129'),
        ('openbook_communities', '0014_auto_20190215_1219'),
    ]

    operations = [
    ]
