# Generated by Django 2.2b1 on 2019-03-09 14:27

from django.db import migrations
import imagekit.models.fields
import openbook_communities.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0017_auto_20190222_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=openbook_communities.helpers.upload_to_community_avatar_directory, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='community',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=openbook_communities.helpers.upload_to_community_cover_directory, verbose_name='cover'),
        ),
    ]
