# Generated by Django 2.2 on 2019-04-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0029_auto_20190423_1921'),
        ('openbook_communities', '0018_auto_20190309_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitylog',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbook_posts.Post'),
        ),
        migrations.AlterField(
            model_name='communitylog',
            name='action_type',
            field=models.CharField(choices=[('B', 'Ban'), ('U', 'Unban'), ('AM', 'Add Moderator'), ('RM', 'Remove Moderator'), ('AA', 'Add Administrator'), ('RA', 'Remove Administrator'), ('RP', 'Remove Post'), ('RPC', 'Remove Post Comment'), ('DPC', 'Disable Post Comments'), ('EPC', 'Enable Post Comments')], editable=False, max_length=5),
        ),
    ]
