# Generated by Django 2.2 on 2019-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0020_auto_20190426_1847'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'user', 'is_administrator'], name='openbook_co_communi_bdd180_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'user', 'is_moderator'], name='openbook_co_communi_ca0147_idx'),
        ),
    ]
