# Generated by Django 2.2 on 2019-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0021_auto_20190502_1754'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='communitymembership',
            index=models.Index(fields=['community', 'user'], name='openbook_co_communi_59b23c_idx'),
        ),
    ]
