# Generated by Django 2.2 on 2019-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0022_auto_20190502_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='hide_content_after_reports_amount',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='hide content after reports amount'),
        ),
        migrations.AddField(
            model_name='community',
            name='is_locked_down',
            field=models.BooleanField(default=False, verbose_name='is locked down'),
        ),
        migrations.AddField(
            model_name='community',
            name='lock_down_after_amount_of_pending_moderation',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='lockdown after amount of pending moderation'),
        ),
    ]
