# Generated by Django 2.2 on 2019-05-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0023_auto_20190512_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='lock_down_after_amount_of_pending_moderation',
            new_name='lock_down_after_pending_moderation_amount',
        ),
    ]
