# Generated by Django 2.2 on 2019-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0024_auto_20190512_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='hide_content_after_reports_amount',
        ),
        migrations.RemoveField(
            model_name='community',
            name='is_locked_down',
        ),
        migrations.RemoveField(
            model_name='community',
            name='lock_down_after_pending_moderation_amount',
        ),
    ]
