# Generated by Django 2.2 on 2019-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0027_auto_20190605_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.TextField(max_length=5000, null=True, verbose_name='rules'),
        ),
    ]
