# Generated by Django 2.2.5 on 2019-11-07 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0029_communitypostsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypostsubscription',
            old_name='user',
            new_name='subscriber',
        ),
        migrations.AlterUniqueTogether(
            name='communitypostsubscription',
            unique_together={('community', 'subscriber')},
        ),
    ]
