# Generated by Django 2.2.5 on 2019-12-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0029_communitynotificationssubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynotificationssubscription',
            name='new_posts_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
