# Generated by Django 2.2.5 on 2019-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0031_auto_20191206_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotificationssubscription',
            name='new_posts_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
