# Generated by Django 2.2.5 on 2019-11-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0031_communitynotificationsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPostSubscription',
        ),
    ]
