# Generated by Django 2.2.5 on 2020-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0034_trendingcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='activity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
