# Generated by Django 2.2.5 on 2020-02-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0035_community_activity_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingCommunity',
        ),
    ]
