# Generated by Django 2.1.5 on 2019-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0005_auto_20190205_1754'),
        ('openbook_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='communities',
            field=models.ManyToManyField(related_name='communities', to='openbook_communities.Community'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='openbook_communities.Community'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Just a random tag title', max_length=64, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
    ]
