# Generated by Django 2.1.5 on 2019-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_tags', '0002_auto_20190206_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description_en',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description_es',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title_es',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
    ]
