# Generated by Django 2.1.5 on 2019-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0001_initial'),
        ('openbook_tags', '0003_auto_20190206_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='verified',
        ),
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ManyToManyField(related_name='tags', to='openbook_categories.Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='name'),
        ),
    ]
