# Generated by Django 2.2.5 on 2019-11-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_tags', '0005_auto_20190208_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
