# Generated by Django 2.2.5 on 2019-11-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_tags', '0007_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(related_name='hashtags', to='openbook_communities.Community'),
        ),
    ]
