# Generated by Django 2.1.3 on 2018-12-04 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_follows', '0006_auto_20181025_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='list',
        ),
    ]
