# Generated by Django 2.2.5 on 2020-01-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_follows', '0007_remove_follow_list'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed_user', 'user'], name='openbook_fo_followe_a71981_idx'),
        ),
    ]
