# Generated by Django 2.1.2 on 2018-10-22 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openbook_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_posts', '0002_auto_20181022_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('color', models.CharField(max_length=7, validators=[openbook_common.validators.hex_color_validator], verbose_name='color')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(related_name='circles', to='openbook_posts.Post')),
            ],
        ),
    ]
