# Generated by Django 2.1.3 on 2018-12-01 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_circles', '0002_auto_20181022_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circles', to=settings.AUTH_USER_MODEL),
        ),
    ]
