# Generated by Django 2.1.3 on 2018-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_connections', '0005_remove_connection_circle'),
        ('openbook_circles', '0003_auto_20181201_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(related_name='circles', to='openbook_connections.Connection'),
        ),
    ]
