# Generated by Django 2.2b1 on 2019-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_circles', '0005_circle_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(db_index=True, related_name='circles', to='openbook_posts.Post'),
        ),
    ]
