# Generated by Django 2.2b1 on 2019-03-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_circles', '0006_auto_20190331_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(db_index=True, related_name='circles', to='openbook_connections.Connection'),
        ),
    ]
