# Generated by Django 2.2b1 on 2019-04-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_circles', '0007_auto_20190401_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='connections',
            field=models.ManyToManyField(related_name='circles', to='openbook_connections.Connection'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='posts',
            field=models.ManyToManyField(related_name='circles', to='openbook_posts.Post'),
        ),
    ]
