# Generated by Django 2.2 on 2019-04-14 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_circles', '0009_auto_20190401_2134'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='circle',
            index_together={('creator', 'id')},
        ),
    ]
