# Generated by Django 2.2 on 2019-04-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_circles', '0010_auto_20190414_1907'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='circle',
            index_together=set(),
        ),
    ]
