# Generated by Django 2.2 on 2019-04-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('openbook_connections', '0013_auto_20190414_1953'),
        ('openbook_circles', '0011_auto_20190414_1915'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='ConnectionCircle',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ],
                options={
                    'db_table': 'openbook_circles_circle_connections',
                },
            ),
            migrations.AlterField(
                model_name='circle',
                name='connections',
                field=models.ManyToManyField(db_index=True, related_name='circles',
                                             through='openbook_circles.ConnectionCircle',
                                             to='openbook_connections.Connection'),
            ),
            migrations.AddField(
                model_name='connectioncircle',
                name='circle',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_circles.Circle'),
            ),
            migrations.AddField(
                model_name='connectioncircle',
                name='connection',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                        to='openbook_connections.Connection'),
            ),
        ])
    ]
