# Generated by Django 2.1.5 on 2019-02-07 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0005_auto_20190205_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('title_es', models.CharField(max_length=64, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=64, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='description')),
                ('description_es', models.CharField(max_length=64, null=True, verbose_name='description')),
                ('description_en', models.CharField(max_length=64, null=True, verbose_name='description')),
                ('created', models.DateTimeField(editable=False)),
                ('avatar', models.ImageField(null=True, upload_to='', verbose_name='avatar')),
                ('communities', models.ManyToManyField(related_name='communities', to='openbook_communities.Community')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
