# Generated by Django 2.1.5 on 2019-02-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='communities',
            field=models.ManyToManyField(related_name='categories', to='openbook_communities.Community'),
        ),
    ]
