# Generated by Django 2.1.5 on 2019-02-12 16:06

from django.db import migrations, models
import openbook_common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0002_auto_20190207_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[openbook_common.validators.hex_color_validator], verbose_name='color'),
            preserve_default=False,
        ),
    ]
