# Generated by Django 2.1.5 on 2019-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0003_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
