# Generated by Django 2.2rc1 on 2019-03-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0004_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='categories', to='openbook_communities.Community'),
        ),
    ]
