# Generated by Django 2.2rc1 on 2019-04-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0005_auto_20190327_1945'),
        ('openbook_categories', '0005_auto_20190330_1554'),
    ]

    operations = [
    ]
