# Generated by Django 2.2.3 on 2019-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0006_merge_20190402_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_de',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
    ]
