# Generated by Django 2.2.4 on 2019-08-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_categories', '0007_auto_20190801_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_it',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_pt_br',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_sv',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_tr',
            field=models.CharField(max_length=64, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_fr',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_it',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_pt_br',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_sv',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_tr',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
    ]
