# Generated by Django 2.1.4 on 2019-01-02 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_invitations', '0002_auto_20190101_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='invited_date',
            field=models.DateField(auto_now_add=True, verbose_name='invited date'),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
