# Generated by Django 2.1.4 on 2019-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_invitations', '0004_auto_20190102_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='invite_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
