# Generated by Django 2.1.5 on 2019-01-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_invitations', '0008_auto_20190107_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinvite',
            old_name='invite_email_sent',
            new_name='is_invite_email_sent',
        ),
    ]
