# Generated by Django 2.1.5 on 2019-01-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_invitations', '0009_auto_20190107_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvite',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
