# Generated by Django 2.1.5 on 2019-02-05 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0012_auto_20190202_1320'),
        ('openbook_invitations', '0010_auto_20190108_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvite',
            name='badge_keyword',
        ),
        migrations.AddField(
            model_name='userinvite',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbook_common.Badge'),
        ),
    ]
