# Generated by Django 2.2 on 2019-04-14 21:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_invitations', '0014_auto_20190413_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinvite',
            unique_together={('invited_by', 'email'), ('invited_by', 'nickname')},
        ),
    ]
