# Generated by Django 2.1.7 on 2019-02-28 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0016_auto_20190214_1525'),
        ('openbook_notifications', '0002_notification_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReactionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.PostReaction')),
            ],
        ),
    ]
