# Generated by Django 2.2b1 on 2019-03-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0017_auto_20190222_1317'),
        ('openbook_notifications', '0005_auto_20190306_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityInviteNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_communities.CommunityInvite')),
            ],
        ),
    ]
