# Generated by Django 2.2 on 2019-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_notifications', '0006_communityinvitenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
    ]
