# Generated by Django 2.2.2 on 2019-06-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0036_auto_20190621_1056'),
        ('openbook_notifications', '0010_auto_20190621_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReactionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.PostComment')),
            ],
        ),
    ]
