# Generated by Django 2.2.2 on 2019-06-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0036_auto_20190621_1056'),
        ('openbook_notifications', '0011_postcommentreactionnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentreactionnotification',
            name='post_comment',
        ),
        migrations.AddField(
            model_name='postcommentreactionnotification',
            name='post_comment_reaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.PostCommentReaction'),
            preserve_default=False,
        ),
    ]
