# Generated by Django 2.2.4 on 2019-08-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0038_postcommentusermention_postusermention'),
        ('openbook_notifications', '0012_auto_20190623_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUserMentionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_user_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.PostUserMention')),
            ],
        ),
        migrations.CreateModel(
            name='PostCommentUserMentionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment_user_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.PostCommentUserMention')),
            ],
        ),
    ]
