# Generated by Django 2.2.4 on 2019-08-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_notifications', '0013_auto_20190801_1650'),
        ('openbook_notifications', '0013_auto_20190808_1719'),
    ]

    operations = [
    ]
