# Generated by Django 2.2.5 on 2019-11-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0047_auto_20191126_1628'),
        ('openbook_posts', '0065_auto_20191013_1133'),
        ('openbook_communities', '0029_communitynotificationssubscription'),
        ('openbook_notifications', '0016_auto_20191106_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PR', 'Post Reaction'), ('PC', 'Post Comment'), ('PCR', 'Post Comment Reply'), ('PCRA', 'Post Comment Reaction'), ('CR', 'Connection Request'), ('CC', 'Connection Confirmed'), ('F', 'Follow'), ('CI', 'Community Invite'), ('PUM', 'Post user mention'), ('PCUM', 'Post comment user mention'), ('CNP', 'New post in community'), ('UNP', 'New post by user')], max_length=5),
        ),
        migrations.CreateModel(
            name='UserNewPostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.Post')),
                ('user_notifications_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_auth.UserNotificationsSubscription')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityNewPostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_notifications_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_communities.CommunityNotificationsSubscription')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.Post')),
            ],
        ),
    ]
