# Generated by Django 2.2.5 on 2019-11-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0029_communitypostsubscription'),
        ('openbook_notifications', '0016_auto_20191106_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNewPostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_post_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_communities.CommunityPostSubscription')),
            ],
        ),
    ]
