# Generated by Django 2.2.12 on 2020-05-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_follows', '0009_auto_20200510_1634'),
        ('openbook_notifications', '0017_auto_20191126_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequestNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_follows.FollowRequest')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequestApprovedNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_follows.Follow')),
            ],
        ),
    ]
