# Generated by Django 2.2.12 on 2020-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_notifications', '0018_followrequestapprovednotification_followrequestnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PR', 'Post Reaction'), ('PC', 'Post Comment'), ('PCR', 'Post Comment Reply'), ('PCRA', 'Post Comment Reaction'), ('CR', 'Connection Request'), ('CC', 'Connection Confirmed'), ('F', 'Follow'), ('FR', 'Follow request'), ('FRA', 'Follow request approved'), ('CI', 'Community Invite'), ('PUM', 'Post user mention'), ('PCUM', 'Post comment user mention'), ('CNP', 'New post in community'), ('UNP', 'New post by user')], max_length=5),
        ),
    ]
