# Generated by Django 2.2.5 on 2019-11-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0065_auto_20191013_1133'),
        ('openbook_notifications', '0018_auto_20191107_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynewpostnotification',
            name='post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.Post'),
            preserve_default=False,
        ),
    ]
