# Generated by Django 2.2.5 on 2020-03-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_notifications', '0019_postsubscriptioncommentnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSubscriptionCommentNotification',
        ),
    ]
