# Generated by Django 2.2.5 on 2019-11-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0065_auto_20191013_1133'),
        ('openbook_auth', '0048_usernotificationssettings_user_new_post_notifications'),
        ('openbook_notifications', '0020_auto_20191116_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewPostNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_posts.Post')),
                ('user_notification_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_auth.UserNotificationSubscription')),
            ],
        ),
    ]
