# Generated by Django 2.2.5 on 2019-11-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0049_auto_20191126_1312'),
        ('openbook_notifications', '0022_remove_usernewpostnotification_user_notification_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernewpostnotification',
            name='user_notifications_subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='openbook_auth.UserNotificationsSubscription'),
            preserve_default=False,
        ),
    ]
