# Generated by Django 2.1.3 on 2018-12-02 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_importer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='data',
            new_name='post',
        ),
    ]
