# Generated by Django 2.1.5 on 2019-01-18 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_hash', models.CharField(max_length=64, unique=True)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_import', to='openbook_importer.Import')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
