# Generated by Django 2.1.5 on 2019-01-25 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_importer', '0002_importedfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedfriend',
            name='data_import',
        ),
        migrations.RemoveField(
            model_name='importedfriend',
            name='user',
        ),
        migrations.AddField(
            model_name='importedfriend',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importedfriend',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
