# Generated by Django 2.1.4 on 2018-12-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_importer', '0002_auto_20181202_0309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
