# Generated by Django 2.1.5 on 2019-02-02 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_importer', '0003_auto_20190125_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
