# Generated by Django 2.1.5 on 2019-02-02 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_importer', '0006_auto_20190202_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL),
        ),
    ]
