# Generated by Django 2.1.5 on 2019-02-09 15:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_importer', '0007_auto_20190202_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
