# Generated by Django 2.1.2 on 2018-10-23 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_circles', '0002_auto_20181022_1712'),
        ('openbook_auth', '0004_auto_20181022_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connections_circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='openbook_circles.Circle'),
        ),
        migrations.AddField(
            model_name='user',
            name='world_circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='openbook_circles.Circle'),
        ),
    ]
