# Generated by Django 2.1.2 on 2018-10-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0005_auto_20181023_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connections_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='openbook_circles.Circle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='world_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='openbook_circles.Circle'),
        ),
    ]
