# Generated by Django 2.1.3 on 2018-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0006_auto_20181025_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=150, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(null=True, upload_to='', verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='followers_count_visible',
            field=models.BooleanField(default=False, verbose_name='followers count visible'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=192, verbose_name='name'),
        ),
    ]
