# Generated by Django 2.1.3 on 2018-11-23 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('openbook_auth', '0008_auto_20181123_1351'),
    ]

    operations = [
    ]
