# Generated by Django 2.1.3 on 2018-11-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0009_remove_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.URLField(null=True, verbose_name='url'),
        ),
    ]
