# Generated by Django 2.1.3 on 2018-12-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0010_userprofile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='world_circle',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=64, null=True, verbose_name='location'),
        ),
    ]
