# Generated by Django 2.1.3 on 2018-12-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0011_auto_20181205_1205'),
        ('openbook_auth', '0011_auto_20181204_1128'),
    ]

    operations = [
    ]
