# Generated by Django 2.1.4 on 2018-12-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0013_badge_userprofilebadge'),
        ('openbook_common', '0009_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilebadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbook_common.Badge'),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
