# Generated by Django 2.1.4 on 2019-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0014_auto_20181231_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_age_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
