# Generated by Django 2.1.5 on 2019-01-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0015_auto_20190104_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='legal_age_confirmation',
            new_name='is_of_legal_age',
        ),
    ]
