# Generated by Django 2.1.5 on 2019-02-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0012_auto_20190202_1320'),
        ('openbook_auth', '0017_auto_20190201_1727'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofilebadge',
            unique_together={('user_profile', 'badge')},
        ),
    ]
