# Generated by Django 2.1.5 on 2019-02-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0018_auto_20190204_1325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofilebadge',
            unique_together=set(),
        ),
    ]
