# Generated by Django 2.1.5 on 2019-02-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0019_auto_20190205_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilebadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userprofilebadge',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='UserProfileBadge',
        ),
    ]
