# Generated by Django 2.1.5 on 2019-02-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0012_auto_20190202_1320'),
        ('openbook_auth', '0020_auto_20190205_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badges',
            field=models.ManyToManyField(related_name='users_profiles', to='openbook_common.Badge'),
        ),
    ]
