# Generated by Django 2.1.5 on 2019-02-20 14:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0021_userprofile_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='', verbose_name='cover'),
        ),
    ]
