# Generated by Django 2.1.5 on 2019-03-03 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0022_auto_20190220_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_comment_notifications', models.BooleanField(default=True, verbose_name='post comment notifications')),
                ('post_reaction_notifications', models.BooleanField(default=True, verbose_name='post reaction notifications')),
                ('follow_notifications', models.BooleanField(default=True, verbose_name='follow notifications')),
                ('connection_request_notifications', models.BooleanField(default=True, verbose_name='connection request notifications')),
                ('connection_confirmed_notifications', models.BooleanField(default=True, verbose_name='connection confirmed notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
