# Generated by Django 2.2b1 on 2019-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0024_auto_20190303_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='community_invite_notifications',
            field=models.BooleanField(default=True, verbose_name='community invite notifications'),
        ),
    ]
