# Generated by Django 2.2b1 on 2019-03-09 14:27

from django.db import migrations
import imagekit.models.fields
import openbook_auth.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0025_usernotificationssettings_community_invite_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=openbook_auth.helpers.upload_to_user_avatar_directory, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=openbook_auth.helpers.upload_to_user_cover_directory, verbose_name='cover'),
        ),
    ]
