# Generated by Django 2.2b1 on 2019-03-11 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0026_auto_20190309_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connections_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbook_circles.Circle'),
        ),
    ]
