# Generated by Django 2.2b1 on 2019-03-11 16:51

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    User = apps.get_model('openbook_auth', 'User')
    for user in User.objects.all():
        user.uuid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('openbook_auth', '0027_auto_20190311_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(create_uuid),
    ]
