# Generated by Django 2.2b1 on 2019-03-11 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0028_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
