# Generated by Django 2.2 on 2019-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0029_auto_20190311_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_count',
            field=models.IntegerField(default=0),
        ),
    ]
