# Generated by Django 2.2 on 2019-04-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0030_auto_20190414_1918'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='userprofile',
            index_together={('id', 'user')},
        ),
    ]
