# Generated by Django 2.2 on 2019-04-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0031_auto_20190410_1614'),
        ('openbook_auth', '0031_auto_20190414_1946'),
    ]

    operations = [
    ]
