# Generated by Django 2.2 on 2019-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0032_merge_20190422_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='are_guidelines_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
