# Generated by Django 2.2 on 2019-05-02 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0034_userblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblock',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
