# Generated by Django 2.2 on 2019-05-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0035_auto_20190502_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='post_comment_reply_notifications',
            field=models.BooleanField(default=True, verbose_name='post comment reply notifications'),
        ),
    ]
