# Generated by Django 2.2 on 2019-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0035_auto_20190502_1754'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked_user', 'blocker'], name='openbook_au_blocked_3369e6_idx'),
        ),
    ]
