# Generated by Django 2.2 on 2019-05-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0036_auto_20190502_1804'),
        ('openbook_auth', '0036_usernotificationssettings_post_comment_reply_notifications'),
    ]

    operations = [
    ]
