# Generated by Django 2.2 on 2019-05-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0037_user_is_deleted'),
        ('openbook_auth', '0037_merge_20190516_1912'),
    ]

    operations = [
    ]
