# Generated by Django 2.2 on 2019-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0038_merge_20190522_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=1000, null=True, verbose_name='bio'),
        ),
    ]
