# Generated by Django 2.2 on 2019-06-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0039_auto_20190605_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('name_es', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbook_auth.UserLanguage'),
        ),
    ]
