# Generated by Django 2.2.2 on 2019-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0040_auto_20190606_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='post_comment_reaction_notifications',
            field=models.BooleanField(default=True, verbose_name='post comment reaction notifications'),
        ),
    ]
