# Generated by Django 2.2.2 on 2019-07-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0040_user_language'),
        ('openbook_auth', '0041_usernotificationssettings_post_comment_reaction_notifications'),
    ]

    operations = [
    ]
