# Generated by Django 2.2.2 on 2019-07-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0014_auto_20190709_1919'),
        ('openbook_auth', '0042_merge_20190702_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='translation_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_users', to='openbook_common.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='openbook_common.Language'),
        ),
    ]
