# Generated by Django 2.2.4 on 2019-08-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0044_auto_20190812_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community_posts_visible',
            field=models.BooleanField(default=True, verbose_name='community posts visible'),
        ),
    ]
