# Generated by Django 2.2.5 on 2019-12-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0047_auto_20191126_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssubscription',
            name='new_posts_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
