# Generated by Django 2.2.5 on 2019-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0047_usernotificationsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='user_new_post_notifications',
            field=models.BooleanField(default=True, verbose_name='user new post notifications'),
        ),
    ]
