# Generated by Django 2.2.5 on 2019-11-26 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_notifications', '0022_remove_usernewpostnotification_user_notification_subscription'),
        ('openbook_auth', '0048_usernotificationssettings_user_new_post_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subscriber')},
            },
        ),
        migrations.DeleteModel(
            name='UserNotificationSubscription',
        ),
    ]
