# Generated by Django 2.2.5 on 2019-12-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0049_auto_20191206_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernotificationssubscription',
            old_name='new_posts_notifications_enabled',
            new_name='new_post_notifications',
        ),
    ]
