# Generated by Django 2.2.5 on 2019-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0050_auto_20191209_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationssubscription',
            name='new_post_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
