# Generated by Django 2.2.12 on 2020-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0051_auto_20191209_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.CharField(choices=[('P', 'Public'), ('T', 'Private')], default='T', editable=False, max_length=2),
        ),
    ]
