# Generated by Django 2.2.10 on 2020-04-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0052_usernotificationssettings_post_subscription_comment_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_subscription_comment_notifications',
        ),
    ]
