# Generated by Django 2.2.12 on 2020-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0052_user_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationssettings',
            name='follow_request_approved_notifications',
            field=models.BooleanField(default=True, verbose_name='follow request approved notifications'),
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='follow_request_notifications',
            field=models.BooleanField(default=True, verbose_name='follow request notifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='visibility',
            field=models.CharField(choices=[('P', 'Public'), ('T', 'Private'), ('O', 'Okuna')], default='O', editable=False, max_length=2),
        ),
    ]
