# Generated by Django 2.2.12 on 2020-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0053_remove_usernotificationssettings_post_subscription_comment_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_reaction_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_reply_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_comment_user_mention_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_reaction_notifications',
        ),
        migrations.RemoveField(
            model_name='usernotificationssettings',
            name='post_user_mention_notifications',
        ),
        migrations.AddField(
            model_name='usernotificationssettings',
            name='post_notifications',
            field=models.BooleanField(default=True, verbose_name='post notifications'),
        ),
    ]
