# Generated by Django 2.1.2 on 2018-10-22 14:55

from django.db import migrations, models
import openbook_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('shortcut', models.CharField(max_length=16, verbose_name='shortcut')),
                ('color', models.CharField(max_length=7, validators=[openbook_common.validators.hex_color_validator], verbose_name='color')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
    ]
