# Generated by Django 2.1.3 on 2018-11-19 16:02

from django.db import migrations, models
import django.db.models.deletion
import openbook_common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0003_auto_20181119_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, unique=True, verbose_name='keyword')),
                ('color', models.CharField(max_length=7, validators=[openbook_common.validators.hex_color_validator], verbose_name='color')),
                ('order', models.IntegerField(default=100)),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='emoji',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emojis', to='openbook_common.EmojiGroup'),
        ),
    ]
