# Generated by Django 2.1.4 on 2018-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0004_auto_20181119_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojigroup',
            name='is_reaction_group',
            field=models.BooleanField(default=False, verbose_name='is reaction group'),
        ),
    ]
