# Generated by Django 2.1.4 on 2018-12-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0005_emojigroup_is_reaction_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='emoji',
            name='keyword_en',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='keyword_es',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emojigroup',
            name='keyword_en',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emojigroup',
            name='keyword_es',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='keyword'),
        ),
    ]
