# Generated by Django 2.1.4 on 2018-12-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0007_auto_20181221_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='keyword',
            field=models.CharField(max_length=16, verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='keyword_en',
            field=models.CharField(max_length=16, null=True, verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='keyword_es',
            field=models.CharField(max_length=16, null=True, verbose_name='keyword'),
        ),
    ]
