# Generated by Django 2.1.4 on 2018-12-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0008_auto_20181221_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=16, verbose_name='keyword')),
            ],
        ),
    ]
