# Generated by Django 2.1.5 on 2019-02-09 15:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0008_auto_20181221_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(unique=True, upload_to='', verbose_name='image'),
        ),
    ]
