# Generated by Django 2.1.5 on 2019-02-02 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0010_auto_20190101_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_description',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='keyword_description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_en',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_es',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='keyword',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
