# Generated by Django 2.1.5 on 2019-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0011_auto_20190202_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='keyword_en',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='keyword_es',
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_description_en',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_description_es',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='keyword_description',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
    ]
