# Generated by Django 2.2.2 on 2019-06-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0012_auto_20190202_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('name_es', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='name')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
    ]
