# Generated by Django 2.2.3 on 2019-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0014_auto_20190709_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='keyword_description_de',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='keyword_de',
            field=models.CharField(max_length=16, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emojigroup',
            name='keyword_de',
            field=models.CharField(max_length=32, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_de',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
    ]
