# Generated by Django 2.2.4 on 2019-08-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0016_auto_20190808_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
