# Generated by Django 2.2.4 on 2019-08-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0017_auto_20190814_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyWhitelistDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=150)),
            ],
        ),
    ]
