# Generated by Django 2.2.5 on 2019-09-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0018_proxywhitelistdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='keyword_description_da',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_description_hu',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
        migrations.AddField(
            model_name='badge',
            name='keyword_description_nl',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='keyword_description'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='keyword_da',
            field=models.CharField(max_length=16, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='keyword_hu',
            field=models.CharField(max_length=16, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emoji',
            name='keyword_nl',
            field=models.CharField(max_length=16, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emojigroup',
            name='keyword_da',
            field=models.CharField(max_length=32, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emojigroup',
            name='keyword_hu',
            field=models.CharField(max_length=32, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='emojigroup',
            name='keyword_nl',
            field=models.CharField(max_length=32, null=True, verbose_name='keyword'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_da',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_hu',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_nl',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
    ]
