# Generated by Django 2.2.5 on 2019-09-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0019_auto_20190909_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProxyWhitelistDomain',
            new_name='ProxyBlacklistedDomain',
        ),
    ]
