# Generated by Django 2.2.5 on 2019-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0020_auto_20190917_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyblacklisteddomain',
            name='domain',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
