# Generated by Django 2.1.2 on 2018-10-22 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.BooleanField(default=True, verbose_name='following')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='openbook_circles.Circle')),
                ('target_connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openbook_connections.Connection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
