# Generated by Django 2.1.2 on 2018-10-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_connections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='following',
        ),
        migrations.AlterField(
            model_name='connection',
            name='circle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='openbook_circles.Circle'),
        ),
    ]
