# Generated by Django 2.1.2 on 2018-10-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_connections', '0002_auto_20181023_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='target_connection',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='openbook_connections.Connection'),
        ),
    ]
