# Generated by Django 2.1.3 on 2018-12-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_connections', '0004_auto_20181023_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='circle',
        ),
    ]
