# Generated by Django 2.1.3 on 2018-12-13 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_connections', '0008_auto_20181213_1343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('user', 'target_user')},
        ),
    ]
