# Generated by Django 2.2 on 2019-04-14 17:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_connections', '0009_auto_20181213_1347'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='connection',
            index_together={('user', 'target_connection')},
        ),
    ]
