# Generated by Django 2.2 on 2019-04-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_connections', '0010_auto_20190414_1905'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='connection',
            index_together=set(),
        ),
    ]
