# Generated by Django 2.2 on 2019-05-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderatedobjectlog',
            old_name='type',
            new_name='log_type',
        ),
    ]
