# Generated by Django 2.2 on 2019-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationcategory',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='moderationcategory',
            name='description_es',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
    ]
