# Generated by Django 2.2 on 2019-05-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0002_auto_20190512_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationcategory',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='moderationcategory',
            name='title_es',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
    ]
