# Generated by Django 2.2 on 2019-05-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0003_auto_20190512_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderationreport',
            old_name='overview',
            new_name='moderated_object',
        ),
    ]
