# Generated by Django 2.2 on 2019-05-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0005_auto_20190519_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatedobject',
            name='object_audit_snapshot',
        ),
        migrations.AlterField(
            model_name='moderationpenalty',
            name='moderated_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_penalties', to='openbook_moderation.ModeratedObject'),
        ),
    ]
