# Generated by Django 2.2 on 2019-05-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0005_auto_20190514_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedobject',
            name='category',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_objects', to='openbook_moderation.ModerationCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moderationcategory',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='moderationcategory',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='moderationcategory',
            name='title_es',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
    ]
