# Generated by Django 2.2 on 2019-05-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0006_auto_20190521_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderationpenalty',
            old_name='duration',
            new_name='expiration',
        ),
    ]
