# Generated by Django 2.2 on 2019-05-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0007_auto_20190516_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatedobject',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=5),
        ),
        migrations.AlterField(
            model_name='moderatedobject',
            name='object_type',
            field=models.CharField(choices=[('P', 'Post'), ('PC', 'Post Comment'), ('C', 'Community'), ('U', 'User')], max_length=5),
        ),
        migrations.AlterField(
            model_name='moderatedobjectstatuschangedlog',
            name='changed_from',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=5, verbose_name='changed from'),
        ),
        migrations.AlterField(
            model_name='moderatedobjectstatuschangedlog',
            name='changed_to',
            field=models.CharField(max_length=5, verbose_name='changed to'),
        ),
    ]
