# Generated by Django 2.2 on 2019-05-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0007_auto_20190521_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationpenalty',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
