# Generated by Django 2.2 on 2019-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0009_moderationcategory_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratedObjectSubmittedChangedLog',
        ),
        migrations.AlterField(
            model_name='moderatedobjectlog',
            name='log_type',
            field=models.CharField(choices=[('DC', 'Description Changed'), ('AC', 'Status Changed'), ('VC', 'Verified Changed'), ('CC', 'Category Changed')], max_length=5),
        ),
    ]
