# Generated by Django 2.2.5 on 2019-12-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0013_auto_20190909_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatedobject',
            name='object_type',
            field=models.CharField(choices=[('P', 'Post'), ('PC', 'Post Comment'), ('C', 'Community'), ('U', 'User'), ('H', 'Hashtag')], max_length=5),
        ),
    ]
