# Generated by Django 2.2.5 on 2019-11-27 13:34

from django.db import migrations, models
import openbook_common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openbook_communities', '0031_communitynotificationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('color', models.CharField(max_length=7, validators=[openbook_common.validators.hex_color_validator], verbose_name='color')),
                ('created', models.DateTimeField(editable=False)),
                ('posts', models.ManyToManyField(related_name='hashtags', to='openbook_communities.Community')),
            ],
        ),
    ]
