# Generated by Django 2.2.5 on 2019-11-27 15:23

from django.db import migrations, models
import imagekit.models.fields
import openbook_hashtags.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(height_field='height', null=True, upload_to=openbook_hashtags.helpers.upload_to_hashtags_directory, verbose_name='image', width_field='width'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
