# Generated by Django 2.2.5 on 2019-11-30 15:54

from django.db import migrations, models
import openbook_common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_hashtags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[openbook_common.validators.hex_color_validator], verbose_name='text color'),
        ),
    ]
