# Generated by Django 2.2.5 on 2019-11-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_hashtags', '0002_auto_20191127_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
    ]
