# Generated by Django 2.2.5 on 2019-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0065_auto_20191013_1133'),
        ('openbook_hashtags', '0003_remove_hashtag_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='posts',
            field=models.ManyToManyField(related_name='hashtags', to='openbook_posts.Post'),
        ),
    ]
