# Generated by Django 2.2.5 on 2019-11-29 15:30

from django.db import migrations, models
import openbook_hashtags.validators


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0066_auto_20191129_1630'),
        ('openbook_hashtags', '0004_hashtag_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='comments',
            field=models.ManyToManyField(related_name='hashtags', to='openbook_posts.PostComment'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[openbook_hashtags.validators.hashtag_name_validator], verbose_name='name'),
        ),
    ]
