# Generated by Django 2.2.5 on 2019-11-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_common', '0021_auto_20190917_1806'),
        ('openbook_hashtags', '0005_auto_20191129_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='emoji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashtags', to='openbook_common.Emoji'),
        ),
    ]
