# Generated by Django 2.2.5 on 2019-11-29 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_hashtags', '0006_hashtag_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='comments',
            new_name='post_comments',
        ),
    ]
