# Generated by Django 2.1.5 on 2019-03-05 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_devices', '0003_remove_device_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('owner', 'uuid')},
        ),
    ]
