# Generated by Django 2.1.5 on 2019-03-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_devices', '0004_auto_20190305_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='one_signal_player_id',
        ),
    ]
