# Generated by Django 2.1.5 on 2019-03-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_devices', '0005_remove_device_one_signal_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.CharField(editable=False, max_length=64, verbose_name='uuid'),
        ),
    ]
