# Generated by Django 2.1.2 on 2018-10-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0002_auto_20181022_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='emoji',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='openbook_posts.PostReactionEmoji'),
            preserve_default=False,
        ),
    ]
