# Generated by Django 2.1.2 on 2018-10-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0003_postreaction_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='emoji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='openbook_common.Emoji'),
        ),
        migrations.DeleteModel(
            name='PostReactionEmoji',
        ),
    ]
