# Generated by Django 2.1.3 on 2018-11-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0008_auto_20181113_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='openbook_posts.Post'),
            preserve_default=False,
        ),
    ]
