# Generated by Django 2.1.3 on 2018-11-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0011_auto_20181119_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_comments',
            field=models.BooleanField(default=True, editable=False, verbose_name='public comments'),
        ),
        migrations.AddField(
            model_name='post',
            name='public_reactions',
            field=models.BooleanField(default=True, editable=False, verbose_name='public reactions'),
        ),
    ]
