# Generated by Django 2.1.4 on 2018-12-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0012_auto_20181123_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to='', verbose_name='image'),
        ),
    ]
