# Generated by Django 2.1.4 on 2018-12-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0013_auto_20181215_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='', verbose_name='video')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='openbook_posts.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
