# Generated by Django 2.2b1 on 2019-03-11 13:32

from django.db import migrations
import imagekit.models.fields
import openbook_posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0021_auto_20190309_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(height_field='height', null=True, upload_to=openbook_posts.helpers.upload_to_post_image_directory, verbose_name='image', width_field='width'),
        ),
    ]
