# Generated by Django 2.2b1 on 2019-04-04 14:31

from django.db import migrations, models
import django.db.models.deletion
import openbook_posts.helpers
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0023_auto_20190317_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='openbook_posts.Post'),
        ),
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=video_encoding.fields.VideoField(height_field='height', null=True, upload_to=openbook_posts.helpers.upload_to_post_video_directory, verbose_name='video', width_field='width'),
        ),
    ]
