# Generated by Django 2.2 on 2019-04-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0026_auto_20190414_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='created',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
    ]
