# Generated by Django 2.2 on 2019-04-14 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_communities', '0018_auto_20190309_1527'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_posts', '0027_auto_20190414_1721'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='post',
            index_together={('creator', 'community')},
        ),
    ]
