# Generated by Django 2.2 on 2019-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0029_auto_20190423_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
