# Generated by Django 2.2 on 2019-05-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0031_postcomment_parent_comment'),
        ('openbook_posts', '0031_auto_20190521_1850'),
    ]

    operations = [
    ]
