# Generated by Django 2.2 on 2019-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0032_merge_20190522_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='hash',
            field=models.CharField(max_length=64, null=True, verbose_name='hash'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='hash',
            field=models.CharField(max_length=64, null=True, verbose_name='hash'),
        ),
    ]
