# Generated by Django 2.2 on 2019-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0034_auto_20190605_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='text'),
        ),
    ]
