# Generated by Django 2.2.2 on 2019-07-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0036_auto_20190620_1957'),
        ('openbook_posts', '0036_auto_20190621_1056'),
    ]

    operations = [
    ]
