# Generated by Django 2.2.3 on 2019-07-30 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0037_merge_20190702_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLinkPreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=5000)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_preview', to='openbook_posts.Post')),
            ],
            options={
                'unique_together': {('post', 'link')},
            },
        ),
    ]
