# Generated by Django 2.2.4 on 2019-08-09 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0037_merge_20190702_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPreviewLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('link', models.CharField(max_length=5000)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview_link', to='openbook_posts.Post')),
            ],
            options={
                'unique_together': {('post', 'link')},
            },
        ),
    ]
