# Generated by Django 2.2.4 on 2019-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0038_postlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLinkWhitelistDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=126)),
            ],
        ),
    ]
