# Generated by Django 2.2.3 on 2019-07-30 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0038_postlinkpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlinkpreview',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
