# Generated by Django 2.2.4 on 2019-08-12 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_posts', '0038_postcommentusermention_postusermention'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcommentusermention',
            unique_together={('user', 'post_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postusermention',
            unique_together={('user', 'post')},
        ),
    ]
