# Generated by Django 2.2.4 on 2019-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0039_postlinkwhitelistdomain'),
        ('openbook_posts', '0039_auto_20190812_1441'),
    ]

    operations = [
    ]
