# Generated by Django 2.2.4 on 2019-08-21 11:35

from django.db import migrations, models
import openbook_posts.helpers
import video_encoding.fields


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0044_auto_20190821_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvideo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='postvideo',
            name='duration',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='file',
            field=video_encoding.fields.VideoField(height_field='height', null=True, upload_to=openbook_posts.helpers.upload_to_post_video_directory, width_field='width'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
