# Generated by Django 2.2.4 on 2019-08-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0046_auto_20190821_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('PG', 'Processing'), ('P', 'Published')], default='D', max_length=2),
        ),
    ]
