# Generated by Django 2.2.4 on 2019-08-22 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0047_auto_20190821_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='openbook_posts.Post'),
        ),
    ]
