# Generated by Django 2.2.4 on 2019-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0048_postvideo_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='position',
        ),
    ]
