# Generated by Django 2.2.4 on 2019-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0049_remove_postmedia_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='postmedia',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
