# Generated by Django 2.2.4 on 2019-08-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0051_postlink_postlinkwhitelistdomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLinkWhitelistDomain',
        ),
    ]
