# Generated by Django 2.2.4 on 2019-08-26 11:23

from django.db import migrations, models
import imagekit.models.fields
import openbook_posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0052_delete_postlinkwhitelistdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvideo',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(height_field='thumbnail_height', null=True, upload_to=openbook_posts.helpers.upload_to_post_image_directory, verbose_name='thumbnail', width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='thumbnail_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postvideo',
            name='thumbnail_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
