# Generated by Django 2.2.4 on 2019-09-02 13:19

from django.db import migrations
import imagekit.models.fields
import openbook_posts.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0057_auto_20190827_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=openbook_posts.helpers.upload_to_post_image_directory, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=openbook_posts.helpers.upload_to_post_directory, verbose_name='thumbnail'),
        ),
    ]
