# Generated by Django 2.2.5 on 2019-09-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0058_auto_20190902_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_post', to='openbook_posts.Post')),
            ],
        ),
    ]
