# Generated by Django 2.2.5 on 2019-09-17 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('openbook_posts', '0059_auto_20190910_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLink',
        ),
    ]
