# Generated by Django 2.2.5 on 2019-09-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0059_auto_20190910_1800'),
        ('openbook_posts', '0059_toppost'),
    ]

    operations = [
    ]
