# Generated by Django 2.2.5 on 2019-09-12 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0028_auto_20190606_0944'),
        ('openbook_posts', '0060_merge_20190912_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPostCommunityExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_posts_community_exclusions', to='openbook_communities.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_posts_community_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
