# Generated by Django 2.2.5 on 2019-09-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0061_toppostcommunityexclusion'),
        ('openbook_posts', '0060_delete_postlink'),
    ]

    operations = [
    ]
