# Generated by Django 2.2.5 on 2019-10-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0062_merge_20190920_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_post', to='openbook_posts.Post', unique=True),
        ),
    ]
