# Generated by Django 2.2.5 on 2019-11-29 15:30

from django.db import migrations, models
import openbook_posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0065_auto_20191013_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000, null=True, validators=[openbook_posts.validators.post_text_hashtags_validator], verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(max_length=1500, validators=[openbook_posts.validators.post_comment_text_hashtags_validator], verbose_name='text'),
        ),
    ]
