# Generated by Django 2.2.5 on 2019-11-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0065_auto_20191013_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_post', to='openbook_posts.Post')),
            ],
        ),
    ]
