# Generated by Django 2.2.5 on 2019-12-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0066_auto_20191129_1630'),
        ('openbook_posts', '0066_trendingpost'),
    ]

    operations = [
    ]
