# Generated by Django 2.2.5 on 2020-01-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0067_merge_20191202_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
