# Generated by Django 2.2.5 on 2020-01-30 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_communities', '0033_auto_20191209_1337'),
        ('openbook_posts', '0067_merge_20191202_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePostsCommunityExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts_community_exclusions', to='openbook_communities.Community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts_community_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'community')},
            },
        ),
    ]
