# Generated by Django 2.2.5 on 2020-02-25 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_posts', '0068_profilepostscommunityexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotificationsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_notifications', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_subscriptions', to='openbook_posts.Post')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'subscriber')},
            },
        ),
    ]
