# Generated by Django 2.2.5 on 2020-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0068_post_activity_score'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['activity_score'], name='openbook_po_activit_4b4ca7_idx'),
        ),
    ]
