# Generated by Django 2.2.5 on 2020-02-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0069_auto_20200130_1529'),
        ('openbook_posts', '0068_profilepostscommunityexclusion'),
    ]

    operations = [
    ]
