# Generated by Django 2.2.12 on 2020-10-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0069_postlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlink',
            name='has_preview',
            field=models.BooleanField(default=False),
        ),
    ]
