# Generated by Django 2.2.5 on 2020-02-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0069_postnotificationssubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postnotificationssubscription',
            old_name='post_notifications',
            new_name='comment_notifications',
        ),
    ]
