# Generated by Django 2.2.12 on 2020-10-19 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0070_postlink_has_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlink',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='openbook_posts.Post'),
        ),
    ]
