# Generated by Django 2.2.5 on 2020-03-13 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbook_posts', '0070_auto_20200226_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnotificationssubscription',
            name='comment_reaction_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postnotificationssubscription',
            name='reaction_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postnotificationssubscription',
            name='reply_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postnotificationssubscription',
            name='reply_where_commented_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postnotificationssubscription',
            name='comment_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PostCommentNotificationsSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_notifications', models.BooleanField(default=True)),
                ('reply_notifications', models.BooleanField(default=True)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_subscriptions', to='openbook_posts.PostComment')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_notifications_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post_comment', 'subscriber')},
            },
        ),
    ]
