# Generated by Django 2.2.5 on 2020-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0070_merge_20200222_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='activity_score',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=10),
        ),
    ]
