# Generated by Django 2.2.10 on 2020-04-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0071_auto_20200313_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postnotificationssubscription',
            name='comment_reaction_notifications',
        ),
        migrations.RemoveField(
            model_name='postnotificationssubscription',
            name='reply_where_commented_notifications',
        ),
    ]
