# Generated by Django 2.2.5 on 2020-05-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_posts', '0071_auto_20200224_1615'),
        ('openbook_posts', '0072_auto_20200414_1852'),
    ]

    operations = [
    ]
