files:
  "/etc/httpd/conf.d/block_admin.conf" :
    mode: "000644"
    owner: root
    group: root
    content: |
      <LocationMatch "^/admin">
          Require ip 127.0.0.1
          Require forward-dns {{ LB_NAME }}
      </LocationMatch>
