# Generated by Django 2.1.5 on 2019-02-22 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('openbook_reports', '0001_initial'), ('openbook_reports', '0002_auto_20190221_1416'), ('openbook_reports', '0003_auto_20190222_1508')]

    initial = True

    dependencies = [
        ('openbook_posts', '0015_post_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=32, null=True)),
                ('comment', models.CharField(blank=True, max_length=560, null=True)),
                ('created', models.DateTimeField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=32, null=True)),
                ('comment', models.CharField(blank=True, max_length=560, null=True)),
                ('created', models.DateTimeField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.CharField(max_length=128, null=True, verbose_name='description')),
                ('created', models.DateTimeField(editable=False)),
                ('description_en', models.CharField(max_length=128, null=True, verbose_name='description')),
                ('description_es', models.CharField(max_length=128, null=True, verbose_name='description')),
                ('title_en', models.CharField(max_length=64, null=True, verbose_name='title')),
                ('title_es', models.CharField(max_length=64, null=True, verbose_name='title')),
            ],
        ),
        migrations.AddField(
            model_name='postreport',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbook_reports.ReportCategory'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='openbook_posts.Post'),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcommentreport',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='openbook_reports.ReportCategory'),
        ),
        migrations.AddField(
            model_name='postcommentreport',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='openbook_posts.PostComment'),
        ),
        migrations.AddField(
            model_name='postcommentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcommentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=32, null=True),
        ),
    ]
