# Generated by Django 2.1.5 on 2019-02-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='description_en',
            field=models.CharField(max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='description_es',
            field=models.CharField(max_length=128, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='title_en',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='title_es',
            field=models.CharField(max_length=64, null=True, verbose_name='title'),
        ),
    ]
